### ISSUE TITLE
Update Hodges & Leonard credit in LICENSE

### ISSUE THREAD

**Issue by joslloand** [ambisonictoolkit/atk-sounds#4]
From Paul Hodges:

> I note that you list a number of sample soundfiles in your documentation, and that three of them have the address of a long-dead web site.  Fear not!  Those three files are still available at the following addresses:
> 
> http://ambisonic-files.s3.amazonaws.com/AMB/pwh-Purcell-Passacaglia(HowHappy).amb
> http://ambisonic-files.s3.amazonaws.com/JL/orfeo.amb
> https://ambisonic-files.s3.amazonaws.com/JL/jlc2.amb
> 
> In fact, all the files contributed to the old Sound of Space website by myself and John Leonard are available through my website:
> 
> https://ambisonic.info/audio.html

Update [LICENSE](https://github.com/ambisonictoolkit/atk-sounds/blob/master/LICENSE.md)

**Comment by lossius** [comment]
I've updated all but one (the Orfeo recording). This one currently has a permission issue and is not available for download.

This info also need to be updated on the website.
